name: QuickClaims
version: 1.4.6
description: Claim and modify your World Guard regions with speed.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-quickclaims/
main: com.moltendorf.bukkit.quickclaims.Plugin
depend: [ WorldGuard, WGRegionEvents ]
